version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:11.7.0-ce.0'
    restart: always
    environment:
      CADDYFILE: |
        https://ppd-git.mlfmonde.org {
          proxy / http://$CONTAINER:80
        }
        http://ppd-docs.mlfmonde.org {
          proxy / http://$CONTAINER:8090
        }
        https://ppd-docker.mlfmonde.org {
          proxy / http://$CONTAINER:5001
        }
        https://ppd-pages.mlfmonde.org {
          proxy / http://$CONTAINER:8090
        }
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
      - registry:/var/opt/gitlab/gitlab-rails/shared/registry
    ports:
      - "3333:22"
    networks:
      - cluster_default
      - backend

  runner:
    image: 'gitlab/gitlab-runner:v11.7.0'
    restart: always
    volumes:
      - runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

volumes:
  config:
    driver: anybox/buttervolume:latest
  logs:
    driver: anybox/buttervolume:latest
  data:
    driver: anybox/buttervolume:latest
  registry:
    driver: anybox/buttervolume:latest
  runner:
    driver: anybox/buttervolume:latest

networks:
  cluster_default:
    external: true
  backend:
    driver: overlay
  default:
    driver: overlay
