version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:8.17.8-ce.0'
    restart: always
    environment:
      CADDYFILE: |
        https://ppd-git.mlfmonde.org {
          proxy / http://$CONTAINER:80
        }
    ports:
      - "2222:22"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    networks:
      - cluster_default

volumes:
  config:
    driver: anybox/buttervolume:latest
  logs:
    driver: anybox/buttervolume:latest
  data:
    driver: anybox/buttervolume:latest

networks:
  cluster_default:
    external: true
  default:
    driver: overlay
